### ISSUE TITLE
Lights only change when the reverser is manually clicked-dragged by the player

### ISSUE THREAD

**Issue by bigyihsuan** [fauxnik/DerailValleyLocoLightsMod#1]
**The Issue:** The headlights only respond to the reverser being dragged.

**Expected Behavior:** The headlights should respond to the current reverser state.

**Actual Behavior:** The headlights only respond when manually dragged by the player. Neither the reverser keybinds nor the loco remote changes the headlight state.

Lights turned on after game load and diesel start:
![](https://i.imgur.com/RPRxdSN.jpg)

Lights don't change when using the remote:
![](https://i.imgur.com/j3Bi1Vk.jpg)
![](https://i.imgur.com/rjaJh19.jpg)

Lights only change after dragging the reverser:
![](https://i.imgur.com/OQDBR9g.jpg)
![](https://i.imgur.com/usHcgCq.jpg)
![](https://i.imgur.com/J4EOtpZ.jpg)

**Comment by fauxnik** [comment]
Thanks for the detailed bug report @bigyihsuan! I'll investigate when I have some spare time.

**Comment by fauxnik** [comment]
This is fixed in [v1.0.1](https://github.com/fauxnik/DerailValleyLocoLightsMod/releases/tag/v1.0.1).
